### ISSUE TITLE
Config parsing broken

### ISSUE THREAD

**Issue by Carlotronics** [michaelkamprath/multi-service-rtmp-broadcaster#29]
Hello,

It seems that latest commit (#a95d726) break the config parser. Indeed, the parser is looping on this error:
```
multi-service-rtmp-broadcaster | 2020-11-22 22:24:14,966 INFO exited: nginx (exit status 1; not expected)
multi-service-rtmp-broadcaster | 2020-11-22 22:24:15,970 INFO spawned: 'nginx' with pid 22
multi-service-rtmp-broadcaster | Traceback (most recent call last):
multi-service-rtmp-broadcaster |   File "/rtmp-conf-generator.py", line 223, in <module>
multi-service-rtmp-broadcaster |     rtmp_conf = generateConfig(sys.argv[1], sys.argv[2])
multi-service-rtmp-broadcaster |   File "/rtmp-conf-generator.py", line 193, in generateConfig
multi-service-rtmp-broadcaster |     transcode_configs[transcode_config_name] = generateTranscodeConfig(
multi-service-rtmp-broadcaster |   File "/rtmp-conf-generator.py", line 131, in generateTranscodeConfig
multi-service-rtmp-broadcaster |     transcode_config['audioOpts'] = RTMP_TRANSCODE_AUDIO_OPTS_CUSTOM.replace(
multi-service-rtmp-broadcaster | TypeError: replace() argument 2 must be str, not int
multi-service-rtmp-broadcaster | ERROR encountered when generating RTMP configuration.
multi-service-rtmp-broadcaster | 2020-11-22 22:24:17,105 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
multi-service-rtmp-broadcaster | 2020-11-22 22:24:17,105 INFO exited: nginx (exit status 1; not expected)
```

I was using default JSON file, as provided in README file.

After reverting my local copy to previous commit (#88e68c4), things worked fine.

Hope this can help !

**Comment by michaelkamprath** [comment]
Can you show me the configurations JSON you were using (altering the stream Keys, of course)?
